env:
  - DATABASE_TEST=annotations_test

language: ruby

rvm:
  - 2.4.1

cache: bundler

script:
  - bundle exec rake spec

before_script:
  - psql -c 'create database annotations_test;' -U postgres

services:
  - postgresql

notifications:
  slack: yaleits-cct:30ydDArus5pyk5mXEHLG3zSN
