# ----
# Site

title: Annopolis
description: Annotation Server
url: https://github.com/yale-web-technologies/mirador-annotations
baseurl: /mirador-annotations

google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: API
    position: 2
  tasks:
    title: Offline tasks
    position: 3

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - patch
  - delete
  - post
